/** Top-5 rated players per championship team — generated by scripts/generate_champion_rosters.py */

export const CHAMPION_ROSTERS: Record<string, readonly string[]> = {
  '2000-lakers': ["Shaquille O'Neal", "Kobe Bryant", "Lindsey Hunter", "Glen Rice", "Tyronn Lue"],
  '2001-lakers': ["Shaquille O'Neal", "Kobe Bryant", "Derek Fisher", "Rick Fox", "Horace Grant"],
  '2002-lakers': ["Shaquille O'Neal", "Kobe Bryant", "Derek Fisher", "Rick Fox", "Robert Horry"],
  '2003-spurs': ["Tim Duncan", "Tony Parker", "Stephen Jackson", "David Robinson", "Malik Rose"],
  '2004-pistons': ["Mehmet Okur", "Richard Hamilton", "Rasheed Wallace", "Chauncey Billups", "Tayshaun Prince"],
  '2005-spurs': ["Tim Duncan", "Tony Parker", "Manu Ginobili", "Nazr Mohammed", "Bruce Bowen"],
  '2006-heat': ["Dwyane Wade", "Shaquille O'Neal", "Antoine Walker", "Jason Williams", "Udonis Haslem"],
  '2007-spurs': ["Tim Duncan", "Tony Parker", "Manu Ginobili", "Brent Barry", "Michael Finley"],
  '2008-celtics': ["Kevin Garnett", "Paul Pierce", "Ray Allen", "Rajon Rondo", "Sam Cassell"],
  '2009-lakers': ["Kobe Bryant", "Pau Gasol", "Andrew Bynum", "Lamar Odom", "Derek Fisher"],
  '2010-lakers': ["Kobe Bryant", "Pau Gasol", "Andrew Bynum", "Lamar Odom", "Metta World Peace"],
  '2011-mavericks': ["Dirk Nowitzki", "Jason Terry", "Shawn Marion", "Jason Kidd", "Tyson Chandler"],
  '2012-heat': ["LeBron James", "Dwyane Wade", "Chris Bosh", "Mario Chalmers", "Udonis Haslem"],
  '2013-heat': ["LeBron James", "Dwyane Wade", "Chris Bosh", "Ray Allen", "Mario Chalmers"],
  '2014-spurs': ["Tim Duncan", "Tony Parker", "Kawhi Leonard", "Manu Ginobili", "Marco Belinelli"],
  '2015-warriors': ["Stephen Curry", "Klay Thompson", "Draymond Green", "Harrison Barnes", "Andrew Bogut"],
  '2016-cavs': ["LeBron James", "Kyrie Irving", "Kevin Love", "Tristan Thompson", "Matthew Dellavedova"],
  '2017-warriors': ["Kevin Durant", "Stephen Curry", "Klay Thompson", "Draymond Green", "JaVale McGee"],
  '2018-warriors': ["Kevin Durant", "Stephen Curry", "Klay Thompson", "Draymond Green", "JaVale McGee"],
  '2019-raptors': ["Kawhi Leonard", "Kyle Lowry", "Pascal Siakam", "Marc Gasol", "Serge Ibaka"],
  '2020-lakers': ["LeBron James", "Anthony Davis", "Kyle Kuzma", "Markieff Morris", "Dwight Howard"],
  '2021-bucks': ["Giannis Antetokounmpo", "Khris Middleton", "Jrue Holiday", "Bobby Portis", "Brook Lopez"],
  '2022-warriors': ["Stephen Curry", "Klay Thompson", "Jordan Poole", "Andrew Wiggins", "Draymond Green"],
  '2023-nuggets': ["Nikola Jokic", "Jamal Murray", "Michael Porter Jr.", "Aaron Gordon", "Bruce Brown"],
  '2024-celtics': ["Jayson Tatum", "Jaylen Brown", "Kristaps Porzingis", "Derrick White", "Jrue Holiday"],
  '2025-thunder': ["Shai Gilgeous-Alexander", "Jalen Williams", "Chet Holmgren", "Aaron Wiggins", "Luguentz Dort"],
} as const

export function getChampionRoster(championId: string): readonly string[] {
  return CHAMPION_ROSTERS[championId] ?? []
}
